/*
======================================================
Enterprise AI Decision Intelligence Platform

Sprint 2

Module:
Database Infrastructure - Performance Indexes

Author:
Sanjana

Description:
Creates database index mappings to optimize query execution
times for commonly searched fields and table joins.

======================================================
*/

-- Ensure we are connected to the correct database
-- \c enterprise_ai_platform;

-- ============================================================================
-- 1. Text Search & Filter Indexes
-- ============================================================================

-- Optimize searches for product names (using case-insensitive queries, e.g., lower(product_name))
-- Note: A B-Tree index on the name matches prefix/exact searches.
CREATE INDEX idx_products_name 
    ON products (product_name);

-- Optimize searches for supplier names
CREATE INDEX idx_suppliers_name 
    ON suppliers (supplier_name);

-- Optimize searches for category names
CREATE INDEX idx_categories_name 
    ON categories (category_name);

-- Optimize filtering by product brand
CREATE INDEX idx_products_brand 
    ON products (brand);

-- Note: The `sku` column already has an automatic unique index generated by the UNIQUE constraint 
-- defined in the constraints file (`uq_products_sku`), so creating a separate index is not needed.


-- ============================================================================
-- 2. Foreign Key Join Optimizations
-- ============================================================================

-- Speed up queries joining products with their respective categories
CREATE INDEX idx_products_category_id 
    ON products (category_id);

-- Speed up queries joining products with their respective suppliers
CREATE INDEX idx_products_supplier_id 
    ON products (supplier_id);


-- ============================================================================
-- 3. Operational Filter Optimizations
-- ============================================================================

-- Speed up queries filtering items by their active/discontinued status
CREATE INDEX idx_products_status 
    ON products (status);
